# For details on how this file works refer to:
#   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns: [ "*" ]

  # Maintain dependencies for devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/nginx-runtime"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/vue-on-nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/web"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Nuget
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for NPM
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 30  # Fallback cooldown if no other rule applies
      semver-major-days: 30  # Cooldown for major version updates
      semver-minor-days: 30  # Cooldown for minor version updates
      semver-patch-days: 30  # Cooldown for patch updates

  - package-ecosystem: "npm"
    directory: "./infrastructure/jasper-aws-bootstrap"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 30  # Fallback cooldown if no other rule applies
      semver-major-days: 30  # Cooldown for major version updates
      semver-minor-days: 30  # Cooldown for minor version updates
      semver-patch-days: 30  # Cooldown for patch updates
