name: Build Infra

on:
  # When a PR is created targeting master branch
  pull_request:
    branches:
      - master
    paths:
      - 'infrastructure/**'

  # Manual trigger via GH Actions UI
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select target environment'
        required: true
        default: 'lz-dev'
        type: choice
        options:
          - lz-dev
          - lz-test
          - lz-prod
          - dev
          - test
          - prod

env:
  WORKING_DIRECTORY: "./infrastructure/cloud/environments/${{ inputs.environment || 'lz-dev' }}"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || 'lz-dev' }}
    env:
      TF_VAR_app_name: ${{ vars.APP_NAME }}
      TF_VAR_environment: ${{ vars.ENVIRONMENT_NAME }}
      TF_VAR_kms_key_name: ${{ vars.KMS_KEY_NAME }}
      TF_VAR_vpc_id: ${{ vars.VPC_ID }}
      TF_VAR_lambda_memory_size: ${{ vars.LAMBDA_MEMORY_SIZE }}
      TF_VAR_alarm_recipients: ${{ vars.ALARM_RECIPIENTS }}
    permissions:
      id-token: write
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Determine environment
        id: determine-environment
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "environment=lz-dev" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 # v0.1.4
        with:
          sarif_file: tfsec.sarif
          working_directory: ${{ env.WORKING_DIRECTORY }}
          tfsec_args: '--tfvars-file=${{ env.WORKING_DIRECTORY }}/${{ env.environment }}.tfvars'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@cf1bb45a277cb3c205638b2cd5c984db1c46a412 # v4.31.7
        with:
          sarif_file: tfsec.sarif

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-duration-seconds: 1800
          role-session-name: ci-deployment

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        id: init
        run: |
          terraform init -input=false -backend-config=backend.tfvars -var-file=${{ env.environment }}.tfvars
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan (Initial Stack)
        id: plan-initial
        run: |
          terraform plan -target=module.initial -no-color -input=false -var-file=${{ env.environment }}.tfvars
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan (Initial) Status
        if: steps.plan-initial.outcome == 'failure'
        run: exit 1

      - name: Terraform Plan (Main Stack)
        id: plan-main
        run: |
          terraform plan -no-color -input=false -var-file=${{ env.environment }}.tfvars
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan (Main) Status
        if: steps.plan-main.outcome == 'failure'
        run: exit 1
