name: Publish Infra

on:
  # PR targeting master is created or new commits are pushed
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'

  # Manual trigger via GH Actions UI
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select target environment'
        required: true
        default: 'lz-dev'
        type: choice
        options:
          - lz-dev
          - lz-test
          - lz-prod
          - dev
          - test
          - prod

env:
  WORKING_DIRECTORY: "./infrastructure/cloud/environments/${{ inputs.environment || 'lz-dev' }}"
  DUMMY_IMAGE_NAME: dummy-image
  GITHUB_IMAGE_REPO: ghcr.io/bcgov/jasper
  APP_ECR_REPO_URL: ${{ vars.AWS_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.APP_NAME }}-app-repo-${{ inputs.environment || 'lz-dev' }}
  LAMBDA_ECR_REPO_URL: ${{ vars.AWS_ACCOUNT }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.APP_NAME }}-lambda-repo-${{ inputs.environment || 'lz-dev' }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || 'lz-dev' }}
    env:
      TF_VAR_app_name: ${{ vars.APP_NAME }}
      TF_VAR_environment: ${{ vars.ENVIRONMENT_NAME }}
      TF_VAR_kms_key_name: ${{ vars.KMS_KEY_NAME }}
      TF_VAR_vpc_id: ${{ vars.VPC_ID }}
      TF_VAR_lambda_memory_size: ${{ vars.LAMBDA_MEMORY_SIZE }}
      TF_VAR_alarm_recipients: ${{ vars.ALARM_RECIPIENTS }}
    permissions:
      id-token: write
      actions: read
      contents: read
      security-events: write
      packages: write
    steps:
      - name: Determine environment
        id: determine-environment
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "environment=lz-dev" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 # v0.1.4
        with:
          sarif_file: tfsec.sarif
          working_directory: ${{ env.WORKING_DIRECTORY }}
          tfsec_args: '--tfvars-file=${{ env.WORKING_DIRECTORY }}/${{ env.environment }}.tfvars'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@fe4161a26a8629af62121b670040955b330f9af2 # v4.31.6
        with:
          sarif_file: tfsec.sarif

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-duration-seconds: 1800
          role-session-name: ci-deployment

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        id: init
        run: |
          terraform init -input=false -backend-config=backend.tfvars -var-file=${{ env.environment }}.tfvars
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan (Initial Stack)
        id: plan-initial
        run: |
          terraform plan -target=module.initial -no-color -input=false -var-file=${{ env.environment }}.tfvars
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan (Initial) Status
        if: steps.plan-initial.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply (Initial Stack)
        run: |
          terraform apply -target=module.initial --auto-approve -input=false -var-file=${{ env.environment }}.tfvars
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Log in to the GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: |
            ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.0
        with:
          driver: docker

      - name: Build ${{ env.DUMMY_IMAGE_NAME }} image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          push: true
          file: ./docker/dummy-image/Dockerfile.release
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Check dummy-image in App ECR exists
        id: app-ecr-check
        shell: bash
        run: |
          IMAGE_TAG=${{ env.DUMMY_IMAGE_NAME }}
          REPOSITORY_NAME=${{ vars.APP_NAME }}-app-repo-${{ env.environment }}

          IMAGE_EXISTS=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --query "imageDetails[?contains(imageTags, '$IMAGE_TAG')]" --output text)

          if [ -z "$IMAGE_EXISTS" ]; then
            echo "Image with tag $IMAGE_TAG does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "Image with tag $IMAGE_TAG already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Push dummy image to App ECR
        if: steps.app-ecr-check.outputs.exists == 'false'
        shell: bash
        run: |
          echo 'Deploying ${{ env.DUMMY_IMAGE_NAME }} to App ECR'
          docker tag  ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}:latest ${{ env.APP_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
          docker push ${{ env.APP_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}

      - name: Check dummy-image in Lambda ECR exists
        id: lambda-ecr-check
        shell: bash
        run: |
          IMAGE_TAG=${{ env.DUMMY_IMAGE_NAME }}
          REPOSITORY_NAME=${{ vars.APP_NAME }}-lambda-repo-${{ env.environment }}

          IMAGE_EXISTS=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --query "imageDetails[?contains(imageTags, '$IMAGE_TAG')]" --output text)

          if [ -z "$IMAGE_EXISTS" ]; then
            echo "Image with tag $IMAGE_TAG does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "Image with tag $IMAGE_TAG already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Push dummy images to Lambda ECR
        if: steps.lambda-ecr-check.outputs.exists == 'false'
        shell: bash
        run: |
          echo 'Deploying ${{ env.env.DUMMY_IMAGE_NAME }} to Lambda ECR'
          docker tag  ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}:latest ${{ env.LAMBDA_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
          docker push ${{ env.LAMBDA_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}

      - name: Terraform Plan (Main Stack)
        id: plan-main
        run: |
          terraform plan -no-color -input=false -var-file=${{ env.environment }}.tfvars
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan (Main) Status
        if: steps.plan-main.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply (Main Stack)
        run: |
          terraform apply --auto-approve -input=false -var-file=${{ env.environment }}.tfvars
        working-directory: ${{ env.WORKING_DIRECTORY }}
